/*
 * 
 * DETUtils
 *
 * Since 2019., DEntisT
 *
 *
 *
 * - Library core file.
 *
 *
 */

// d_properties

#define DETUTILS_TEXT_MAX_PROPS_REACH "Maximum number of created properties exceeded."
#define DETUTILS_TEXT_PROPERTY_NAME "Property: %s"

#define DETUTILS_TEXT_PROP_LOCK "SERVER: This property's door is locked."
#define DETUTILS_TEXT_TEAMPROP_LOCK "SERVER: Invalid team; try again."

// d_commands

#define DETUTILS_TEXT_UNK_PRX_FUNC "Prefix function name for command %s doesn't exist."

#define DETUTILS_TEXT_CHATMODE_PRX "SERVER: Chat mode switched to custom-prefixed commands mode."
#define DETUTILS_TEXT_CHATMODE_MSG "SERVER: Chat mode switched to plain-text messages mode."

// d_fmargs

// d_visual

#define DETUTILS_TEXT_MAX_GUN_REACH "Maximum number of dropped gun objects exceeded."
#define DETUTILS_TEXT_CMD_TIMER "The player tried to use the command but the timer was not over yet."
#define DETUTILS_TEXT_CANNOT_OPERATE ""D_COLOUR_GREY"Operation can't be completed at the moment."
#define DETUTILS_TEXT_THROW_GUN ""D_COLOUR_GREY"You threw away {ffffff}%s"D_COLOUR_GREY"."
#define DETUTILS_TEXT_NOGUN_NEARBY ""D_COLOUR_GREY"No guns nearby."
#define DETUTILS_TEXT_GUN_DESTROY ""D_COLOUR_GREY"You destroyed {ffffff}%s"D_COLOUR_GREY"."
#define DETUTILS_TEXT_GUN_PICK ""D_COLOUR_GREY"You picked up {ffffff}%s"D_COLOUR_GREY"."

// d_anticheat

// d_colours

// d_mapeditor

#define DETUTILS_TEXT_DIALOG_CONFIRM "Confirm"
#define DETUTILS_TEXT_EXITDIALOG "Cancel"
#define DETUTILS_TEXT_MAPEDITOR_CAPTION "Map Editor"

#define DETUTILS_TEXT_MAPEDITOR_CHOICES "Create object\nDestroy object\nEdit object"
#define DETUTILS_TEXT_MAPEDITOR_OBJID "Please insert the object ID you want to create below:"
#define DETUTILS_TEXT_MAPEDITOR_DSTRY "Please insert the object's ID you want to destroy below:"
#define DETUTILS_TEXT_MAPEDITOR_EDIT "Please insert the object's ID you want to edit below:"