/*
 *
 * DETUtils
 *
 * - d_rem provides the `@rem`
 *   decorator.
 *
 * - Provides rem levels, 
 *   IMPORTANT, HACK, 
 *   BUG and NOTE.
 */

#define @DETUTILSREM_KEYWORD__@%0\32; @DETUTILSREM_KEYWORD__@
#define @rem%0(%1.level%2= @DETUTILSREM_KEYWORD__@

/*
                                                                                      
88b           d88              88                         db         88888888ba   88  
888b         d888              ""                        d88b        88      "8b  88  
88`8b       d8'88                                       d8'`8b       88      ,8P  88  
88 `8b     d8' 88  ,adPPYYba,  88  8b,dPPYba,          d8'  `8b      88aaaaaa8P'  88  
88  `8b   d8'  88  ""     `Y8  88  88P'   `"8a        d8YaaaaY8b     88""""""'    88  
88   `8b d8'   88  ,adPPPPP88  88  88       88       d8""""""""8b    88           88  
88    `888'    88  88,    ,88  88  88       88      d8'        `8b   88           88  
88     `8'     88  `"8bbdP"Y8  88  88       88     d8'          `8b  88           88  
                                                                                      
                                                                                      
*/

#define @DETUTILSREM_KEYWORD__@IMPORTANT%0)%1:%2;
#define @DETUTILSREM_KEYWORD__@HACK%0)%1:%2;
#define @DETUTILSREM_KEYWORD__@NOTE%0)%1:%2;
#define @DETUTILSREM_KEYWORD__@BUG%0)%1:%2;