#define DETUTILS_DEV_MODE
//#define DETUTILS_DEBUG_MODE
//#define DETUTILS_TESTING_MODE
//#define DETUTILS_NO_MODULE_WARNINGS
#define DETUTILS_COMPAT
//#define DETUTILS_DO_LST
//#define DETUTILS_FILTERSCRIPT_MODE
//#define DETUTILS_NO_DISCORDAPI
#define DETUTILS_ALS_CALL_DEBUG
#define DISCORD_COMMAND_PREFIX '!'
#define DETUTILS_FMARGS_FUNCREPLACE
#define DETUTILS_NO_DISCORDAPI

#include <a_samp>

#include "DETUTILS\detutils"

main(){}
