/*
 * 
 * DETUtils
 *
 * Since 2019., DEntisT
 *
 *
 *
 * - A library providing an execution
 *   of code outside functions.
 */

#if defined @DETUTILSGLOBAL_FUNC__

#undef @DETUTILSGLOBAL_FUNC__

#endif

#if defined DETUTILSGLOBAL_IDX

#if DETUTILSGLOBAL_IDX == 0

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (1)

#define @1@%0\32; @1@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @1@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '1'.
#endif

#endinput


#elseif DETUTILSGLOBAL_IDX == 1

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (2)

#define @2@%0\32; @2@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @2@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '2'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 2

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (3)

#define @3@%0\32; @3@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @3@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '3'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 3

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (4)

#define @4@%0\32; @4@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @4@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '4'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 4

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (5)

#define @5@%0\32; @5@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @5@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '5'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 5

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (6)

#define @6@%0\32; @6@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @6@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '6'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 6

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (7)

#define @7@%0\32; @7@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @7@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '7'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 7

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (8)

#define @8@%0\32; @8@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @8@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '8'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 8

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (9)

#define @9@%0\32; @9@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @9@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '9'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 9

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (10)

#define @10@%0\32; @10@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @10@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '10'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 10

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (11)

#define @11@%0\32; @11@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @11@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '11'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 11

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (12)

#define @12@%0\32; @12@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @12@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '12'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 12

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (13)

#define @13@%0\32; @13@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @13@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '13'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 13

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (14)

#define @14@%0\32; @14@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @14@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '14'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 14

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (15)

#define @15@%0\32; @15@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @15@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '15'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 15

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (16)

#define @16@%0\32; @16@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @16@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '16'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 16

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (17)

#define @17@%0\32; @17@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @17@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '17'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 17

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (18)

#define @18@%0\32; @18@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @18@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '18'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 18

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (19)

#define @19@%0\32; @19@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @19@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '19'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 19

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (20)

#define @20@%0\32; @20@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @20@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '20'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 20

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (21)

#define @21@%0\32; @21@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @21@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '21'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 21

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (22)

#define @22@%0\32; @22@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @22@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '22'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 22

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (23)

#define @23@%0\32; @23@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @23@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '23'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 23

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (24)

#define @24@%0\32; @24@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @24@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '24'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 24

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (25)

#define @25@%0\32; @25@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @25@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '25'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 25

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (26)

#define @26@%0\32; @26@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @26@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '26'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 26

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (27)

#define @27@%0\32; @27@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @27@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '27'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 27

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (28)

#define @28@%0\32; @28@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @28@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '28'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 28

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (29)

#define @29@%0\32; @29@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @29@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '29'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 29

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (30)

#define @30@%0\32; @30@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @30@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '30'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 30

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (31)

#define @31@%0\32; @31@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @31@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '31'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 31

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (32)

#define @32@%0\32; @32@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @32@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '32'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 32

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (33)

#define @33@%0\32; @33@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @33@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '33'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 33

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (34)

#define @34@%0\32; @34@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @34@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '34'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 34

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (35)

#define @35@%0\32; @35@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @35@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '35'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 35

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (36)

#define @36@%0\32; @36@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @36@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '36'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 36

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (37)

#define @37@%0\32; @37@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @37@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '37'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 37

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (38)

#define @38@%0\32; @38@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @38@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '38'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 38

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (39)

#define @39@%0\32; @39@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @39@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '39'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 39

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (40)

#define @40@%0\32; @40@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @40@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '40'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 40

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (41)

#define @41@%0\32; @41@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @41@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '41'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 41

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (42)

#define @42@%0\32; @42@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @42@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '42'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 42

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (43)

#define @43@%0\32; @43@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @43@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '43'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 43

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (44)

#define @44@%0\32; @44@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @44@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '44'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 44

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (45)

#define @45@%0\32; @45@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @45@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '45'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 45

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (46)

#define @46@%0\32; @46@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @46@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '46'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 46

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (47)

#define @47@%0\32; @47@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @47@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '47'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 47

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (48)

#define @48@%0\32; @48@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @48@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '48'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 48

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (49)

#define @49@%0\32; @49@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @49@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '49'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 49

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (50)

#define @50@%0\32; @50@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @50@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '50'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 50

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (51)

#define @51@%0\32; @51@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @51@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '51'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 51

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (52)

#define @52@%0\32; @52@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @52@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '52'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 52

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (53)

#define @53@%0\32; @53@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @53@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '53'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 53

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (54)

#define @54@%0\32; @54@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @54@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '54'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 54

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (55)

#define @55@%0\32; @55@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @55@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '55'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 55

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (56)

#define @56@%0\32; @56@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @56@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '56'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 56

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (57)

#define @57@%0\32; @57@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @57@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '57'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 57

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (58)

#define @58@%0\32; @58@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @58@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '58'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 58

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (59)

#define @59@%0\32; @59@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @59@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '59'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 59

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (60)

#define @60@%0\32; @60@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @60@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '60'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 60

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (61)

#define @61@%0\32; @61@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @61@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '61'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 61

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (62)

#define @62@%0\32; @62@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @62@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '62'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 62

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (63)

#define @63@%0\32; @63@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @63@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '63'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 63

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (64)

#define @64@%0\32; @64@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @64@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '64'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 64

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (65)

#define @65@%0\32; @65@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @65@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '65'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 65

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (66)

#define @66@%0\32; @66@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @66@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '66'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 66

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (67)

#define @67@%0\32; @67@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @67@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '67'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 67

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (68)

#define @68@%0\32; @68@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @68@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '68'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 68

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (69)

#define @69@%0\32; @69@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @69@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '69'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 69

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (70)

#define @70@%0\32; @70@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @70@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '70'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 70

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (71)

#define @71@%0\32; @71@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @71@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '71'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 71

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (72)

#define @72@%0\32; @72@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @72@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '72'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 72

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (73)

#define @73@%0\32; @73@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @73@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '73'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 73

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (74)

#define @74@%0\32; @74@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @74@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '74'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 74

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (75)

#define @75@%0\32; @75@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @75@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '75'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 75

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (76)

#define @76@%0\32; @76@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @76@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '76'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 76

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (77)

#define @77@%0\32; @77@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @77@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '77'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 77

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (78)

#define @78@%0\32; @78@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @78@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '78'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 78

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (79)

#define @79@%0\32; @79@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @79@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '79'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 79

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (80)

#define @80@%0\32; @80@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @80@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '80'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 80

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (81)

#define @81@%0\32; @81@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @81@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '81'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 81

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (82)

#define @82@%0\32; @82@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @82@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '82'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 82

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (83)

#define @83@%0\32; @83@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @83@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '83'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 83

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (84)

#define @84@%0\32; @84@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @84@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '84'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 84

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (85)

#define @85@%0\32; @85@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @85@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '85'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 85

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (86)

#define @86@%0\32; @86@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @86@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '86'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 86

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (87)

#define @87@%0\32; @87@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @87@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '87'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 87

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (88)

#define @88@%0\32; @88@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @88@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '88'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 88

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (89)

#define @89@%0\32; @89@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @89@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '89'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 89

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (90)

#define @90@%0\32; @90@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @90@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '90'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 90

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (91)

#define @91@%0\32; @91@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @91@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '91'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 91

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (92)

#define @92@%0\32; @92@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @92@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '92'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 92

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (93)

#define @93@%0\32; @93@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @93@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '93'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 93

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (94)

#define @94@%0\32; @94@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @94@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '94'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 94

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (95)

#define @95@%0\32; @95@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @95@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '95'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 95

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (96)

#define @96@%0\32; @96@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @96@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '96'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 96

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (97)

#define @97@%0\32; @97@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @97@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '97'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 97

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (98)

#define @98@%0\32; @98@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @98@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '98'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 98

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (99)

#define @99@%0\32; @99@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @99@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '99'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 99

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (100)

#define @100@%0\32; @100@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @100@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '100'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 100

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (101)

#define @101@%0\32; @101@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @101@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '101'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 101

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (102)

#define @102@%0\32; @102@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @102@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '102'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 102

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (103)

#define @103@%0\32; @103@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @103@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '103'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 103

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (104)

#define @104@%0\32; @104@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @104@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '104'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 104

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (105)

#define @105@%0\32; @105@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @105@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '105'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 105

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (106)

#define @106@%0\32; @106@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @106@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '106'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 106

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (107)

#define @107@%0\32; @107@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @107@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '107'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 107

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (108)

#define @108@%0\32; @108@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @108@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '108'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 108

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (109)

#define @109@%0\32; @109@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @109@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '109'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 109

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (110)

#define @110@%0\32; @110@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @110@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '110'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 110

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (111)

#define @111@%0\32; @111@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @111@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '111'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 111

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (112)

#define @112@%0\32; @112@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @112@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '112'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 112

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (113)

#define @113@%0\32; @113@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @113@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '113'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 113

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (114)

#define @114@%0\32; @114@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @114@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '114'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 114

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (115)

#define @115@%0\32; @115@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @115@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '115'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 115

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (116)

#define @116@%0\32; @116@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @116@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '116'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 116

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (117)

#define @117@%0\32; @117@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @117@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '117'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 117

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (118)

#define @118@%0\32; @118@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @118@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '118'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 118

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (119)

#define @119@%0\32; @119@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @119@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '119'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 119

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (120)

#define @120@%0\32; @120@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @120@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '120'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 120

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (121)

#define @121@%0\32; @121@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @121@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '121'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 121

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (122)

#define @122@%0\32; @122@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @122@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '122'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 122

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (123)

#define @123@%0\32; @123@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @123@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '123'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 123

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (124)

#define @124@%0\32; @124@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @124@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '124'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 124

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (125)

#define @125@%0\32; @125@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @125@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '125'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 125

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (126)

#define @126@%0\32; @126@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @126@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '126'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 126

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (127)

#define @127@%0\32; @127@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @127@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '127'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 127

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (128)

#define @128@%0\32; @128@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @128@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '128'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 128

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (129)

#define @129@%0\32; @129@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @129@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '129'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 129

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (130)

#define @130@%0\32; @130@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @130@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '130'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 130

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (131)

#define @131@%0\32; @131@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @131@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '131'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 131

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (132)

#define @132@%0\32; @132@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @132@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '132'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 132

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (133)

#define @133@%0\32; @133@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @133@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '133'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 133

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (134)

#define @134@%0\32; @134@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @134@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '134'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 134

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (135)

#define @135@%0\32; @135@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @135@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '135'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 135

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (136)

#define @136@%0\32; @136@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @136@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '136'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 136

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (137)

#define @137@%0\32; @137@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @137@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '137'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 137

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (138)

#define @138@%0\32; @138@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @138@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '138'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 138

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (139)

#define @139@%0\32; @139@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @139@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '139'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 139

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (140)

#define @140@%0\32; @140@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @140@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '140'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 140

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (141)

#define @141@%0\32; @141@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @141@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '141'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 141

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (142)

#define @142@%0\32; @142@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @142@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '142'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 142

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (143)

#define @143@%0\32; @143@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @143@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '143'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 143

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (144)

#define @144@%0\32; @144@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @144@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '144'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 144

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (145)

#define @145@%0\32; @145@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @145@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '145'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 145

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (146)

#define @146@%0\32; @146@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @146@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '146'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 146

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (147)

#define @147@%0\32; @147@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @147@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '147'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 147

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (148)

#define @148@%0\32; @148@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @148@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '148'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 148

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (149)

#define @149@%0\32; @149@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @149@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '149'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 149

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (150)

#define @150@%0\32; @150@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @150@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '150'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 150

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (151)

#define @151@%0\32; @151@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @151@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '151'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 151

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (152)

#define @152@%0\32; @152@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @152@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '152'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 152

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (153)

#define @153@%0\32; @153@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @153@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '153'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 153

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (154)

#define @154@%0\32; @154@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @154@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '154'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 154

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (155)

#define @155@%0\32; @155@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @155@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '155'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 155

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (156)

#define @156@%0\32; @156@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @156@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '156'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 156

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (157)

#define @157@%0\32; @157@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @157@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '157'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 157

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (158)

#define @158@%0\32; @158@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @158@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '158'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 158

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (159)

#define @159@%0\32; @159@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @159@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '159'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 159

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (160)

#define @160@%0\32; @160@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @160@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '160'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 160

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (161)

#define @161@%0\32; @161@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @161@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '161'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 161

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (162)

#define @162@%0\32; @162@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @162@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '162'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 162

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (163)

#define @163@%0\32; @163@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @163@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '163'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 163

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (164)

#define @164@%0\32; @164@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @164@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '164'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 164

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (165)

#define @165@%0\32; @165@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @165@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '165'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 165

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (166)

#define @166@%0\32; @166@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @166@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '166'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 166

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (167)

#define @167@%0\32; @167@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @167@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '167'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 167

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (168)

#define @168@%0\32; @168@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @168@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '168'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 168

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (169)

#define @169@%0\32; @169@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @169@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '169'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 169

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (170)

#define @170@%0\32; @170@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @170@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '170'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 170

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (171)

#define @171@%0\32; @171@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @171@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '171'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 171

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (172)

#define @172@%0\32; @172@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @172@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '172'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 172

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (173)

#define @173@%0\32; @173@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @173@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '173'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 173

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (174)

#define @174@%0\32; @174@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @174@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '174'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 174

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (175)

#define @175@%0\32; @175@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @175@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '175'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 175

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (176)

#define @176@%0\32; @176@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @176@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '176'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 176

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (177)

#define @177@%0\32; @177@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @177@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '177'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 177

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (178)

#define @178@%0\32; @178@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @178@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '178'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 178

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (179)

#define @179@%0\32; @179@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @179@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '179'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 179

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (180)

#define @180@%0\32; @180@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @180@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '180'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 180

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (181)

#define @181@%0\32; @181@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @181@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '181'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 181

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (182)

#define @182@%0\32; @182@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @182@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '182'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 182

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (183)

#define @183@%0\32; @183@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @183@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '183'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 183

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (184)

#define @184@%0\32; @184@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @184@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '184'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 184

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (185)

#define @185@%0\32; @185@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @185@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '185'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 185

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (186)

#define @186@%0\32; @186@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @186@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '186'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 186

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (187)

#define @187@%0\32; @187@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @187@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '187'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 187

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (188)

#define @188@%0\32; @188@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @188@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '188'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 188

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (189)

#define @189@%0\32; @189@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @189@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '189'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 189

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (190)

#define @190@%0\32; @190@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @190@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '190'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 190

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (191)

#define @191@%0\32; @191@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @191@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '191'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 191

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (192)

#define @192@%0\32; @192@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @192@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '192'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 192

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (193)

#define @193@%0\32; @193@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @193@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '193'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 193

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (194)

#define @194@%0\32; @194@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @194@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '194'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 194

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (195)

#define @195@%0\32; @195@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @195@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '195'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 195

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (196)

#define @196@%0\32; @196@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @196@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '196'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 196

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (197)

#define @197@%0\32; @197@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @197@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '197'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 197

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (198)

#define @198@%0\32; @198@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @198@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '198'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 198

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (199)

#define @199@%0\32; @199@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @199@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '199'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 199

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (200)

#define @200@%0\32; @200@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @200@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '200'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 200

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (201)

#define @201@%0\32; @201@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @201@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '201'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 201

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (202)

#define @202@%0\32; @202@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @202@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '202'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 202

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (203)

#define @203@%0\32; @203@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @203@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '203'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 203

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (204)

#define @204@%0\32; @204@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @204@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '204'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 204

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (205)

#define @205@%0\32; @205@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @205@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '205'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 205

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (206)

#define @206@%0\32; @206@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @206@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '206'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 206

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (207)

#define @207@%0\32; @207@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @207@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '207'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 207

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (208)

#define @208@%0\32; @208@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @208@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '208'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 208

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (209)

#define @209@%0\32; @209@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @209@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '209'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 209

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (210)

#define @210@%0\32; @210@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @210@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '210'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 210

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (211)

#define @211@%0\32; @211@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @211@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '211'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 211

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (212)

#define @212@%0\32; @212@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @212@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '212'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 212

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (213)

#define @213@%0\32; @213@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @213@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '213'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 213

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (214)

#define @214@%0\32; @214@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @214@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '214'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 214

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (215)

#define @215@%0\32; @215@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @215@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '215'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 215

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (216)

#define @216@%0\32; @216@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @216@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '216'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 216

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (217)

#define @217@%0\32; @217@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @217@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '217'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 217

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (218)

#define @218@%0\32; @218@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @218@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '218'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 218

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (219)

#define @219@%0\32; @219@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @219@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '219'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 219

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (220)

#define @220@%0\32; @220@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @220@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '220'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 220

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (221)

#define @221@%0\32; @221@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @221@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '221'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 221

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (222)

#define @222@%0\32; @222@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @222@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '222'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 222

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (223)

#define @223@%0\32; @223@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @223@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '223'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 223

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (224)

#define @224@%0\32; @224@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @224@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '224'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 224

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (225)

#define @225@%0\32; @225@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @225@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '225'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 225

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (226)

#define @226@%0\32; @226@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @226@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '226'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 226

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (227)

#define @227@%0\32; @227@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @227@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '227'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 227

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (228)

#define @228@%0\32; @228@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @228@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '228'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 228

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (229)

#define @229@%0\32; @229@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @229@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '229'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 229

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (230)

#define @230@%0\32; @230@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @230@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '230'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 230

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (231)

#define @231@%0\32; @231@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @231@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '231'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 231

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (232)

#define @232@%0\32; @232@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @232@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '232'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 232

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (233)

#define @233@%0\32; @233@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @233@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '233'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 233

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (234)

#define @234@%0\32; @234@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @234@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '234'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 234

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (235)

#define @235@%0\32; @235@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @235@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '235'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 235

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (236)

#define @236@%0\32; @236@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @236@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '236'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 236

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (237)

#define @237@%0\32; @237@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @237@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '237'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 237

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (238)

#define @238@%0\32; @238@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @238@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '238'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 238

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (239)

#define @239@%0\32; @239@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @239@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '239'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 239

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (240)

#define @240@%0\32; @240@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @240@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '240'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 240

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (241)

#define @241@%0\32; @241@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @241@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '241'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 241

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (242)

#define @242@%0\32; @242@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @242@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '242'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 242

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (243)

#define @243@%0\32; @243@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @243@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '243'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 243

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (244)

#define @244@%0\32; @244@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @244@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '244'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 244

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (245)

#define @245@%0\32; @245@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @245@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '245'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 245

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (246)

#define @246@%0\32; @246@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @246@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '246'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 246

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (247)

#define @247@%0\32; @247@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @247@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '247'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 247

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (248)

#define @248@%0\32; @248@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @248@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '248'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 248

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (249)

#define @249@%0\32; @249@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @249@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '249'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 249

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (250)

#define @250@%0\32; @250@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @250@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '250'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 250

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (251)

#define @251@%0\32; @251@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @251@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '251'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 251

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (252)

#define @252@%0\32; @252@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @252@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '252'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 252

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (253)

#define @253@%0\32; @253@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @253@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '253'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 253

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (254)

#define @254@%0\32; @254@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @254@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '254'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 254

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (255)

#define @255@%0\32; @255@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @255@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '255'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 255

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (256)

#define @256@%0\32; @256@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @256@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '256'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 256

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (257)

#define @257@%0\32; @257@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @257@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '257'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 257

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (258)

#define @258@%0\32; @258@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @258@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '258'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 258

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (259)

#define @259@%0\32; @259@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @259@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '259'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 259

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (260)

#define @260@%0\32; @260@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @260@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '260'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 260

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (261)

#define @261@%0\32; @261@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @261@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '261'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 261

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (262)

#define @262@%0\32; @262@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @262@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '262'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 262

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (263)

#define @263@%0\32; @263@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @263@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '263'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 263

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (264)

#define @264@%0\32; @264@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @264@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '264'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 264

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (265)

#define @265@%0\32; @265@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @265@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '265'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 265

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (266)

#define @266@%0\32; @266@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @266@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '266'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 266

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (267)

#define @267@%0\32; @267@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @267@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '267'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 267

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (268)

#define @268@%0\32; @268@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @268@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '268'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 268

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (269)

#define @269@%0\32; @269@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @269@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '269'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 269

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (270)

#define @270@%0\32; @270@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @270@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '270'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 270

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (271)

#define @271@%0\32; @271@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @271@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '271'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 271

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (272)

#define @272@%0\32; @272@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @272@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '272'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 272

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (273)

#define @273@%0\32; @273@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @273@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '273'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 273

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (274)

#define @274@%0\32; @274@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @274@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '274'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 274

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (275)

#define @275@%0\32; @275@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @275@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '275'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 275

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (276)

#define @276@%0\32; @276@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @276@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '276'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 276

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (277)

#define @277@%0\32; @277@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @277@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '277'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 277

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (278)

#define @278@%0\32; @278@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @278@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '278'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 278

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (279)

#define @279@%0\32; @279@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @279@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '279'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 279

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (280)

#define @280@%0\32; @280@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @280@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '280'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 280

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (281)

#define @281@%0\32; @281@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @281@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '281'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 281

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (282)

#define @282@%0\32; @282@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @282@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '282'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 282

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (283)

#define @283@%0\32; @283@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @283@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '283'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 283

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (284)

#define @284@%0\32; @284@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @284@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '284'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 284

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (285)

#define @285@%0\32; @285@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @285@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '285'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 285

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (286)

#define @286@%0\32; @286@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @286@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '286'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 286

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (287)

#define @287@%0\32; @287@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @287@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '287'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 287

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (288)

#define @288@%0\32; @288@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @288@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '288'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 288

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (289)

#define @289@%0\32; @289@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @289@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '289'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 289

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (290)

#define @290@%0\32; @290@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @290@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '290'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 290

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (291)

#define @291@%0\32; @291@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @291@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '291'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 291

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (292)

#define @292@%0\32; @292@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @292@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '292'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 292

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (293)

#define @293@%0\32; @293@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @293@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '293'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 293

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (294)

#define @294@%0\32; @294@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @294@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '294'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 294

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (295)

#define @295@%0\32; @295@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @295@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '295'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 295

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (296)

#define @296@%0\32; @296@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @296@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '296'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 296

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (297)

#define @297@%0\32; @297@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @297@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '297'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 297

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (298)

#define @298@%0\32; @298@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @298@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '298'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 298

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (299)

#define @299@%0\32; @299@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @299@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '299'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 299

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (300)

#define @300@%0\32; @300@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @300@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '300'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 300

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (301)

#define @301@%0\32; @301@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @301@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '301'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 301

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (302)

#define @302@%0\32; @302@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @302@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '302'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 302

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (303)

#define @303@%0\32; @303@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @303@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '303'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 303

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (304)

#define @304@%0\32; @304@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @304@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '304'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 304

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (305)

#define @305@%0\32; @305@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @305@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '305'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 305

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (306)

#define @306@%0\32; @306@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @306@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '306'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 306

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (307)

#define @307@%0\32; @307@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @307@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '307'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 307

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (308)

#define @308@%0\32; @308@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @308@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '308'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 308

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (309)

#define @309@%0\32; @309@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @309@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '309'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 309

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (310)

#define @310@%0\32; @310@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @310@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '310'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 310

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (311)

#define @311@%0\32; @311@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @311@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '311'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 311

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (312)

#define @312@%0\32; @312@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @312@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '312'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 312

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (313)

#define @313@%0\32; @313@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @313@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '313'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 313

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (314)

#define @314@%0\32; @314@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @314@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '314'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 314

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (315)

#define @315@%0\32; @315@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @315@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '315'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 315

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (316)

#define @316@%0\32; @316@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @316@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '316'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 316

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (317)

#define @317@%0\32; @317@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @317@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '317'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 317

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (318)

#define @318@%0\32; @318@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @318@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '318'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 318

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (319)

#define @319@%0\32; @319@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @319@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '319'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 319

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (320)

#define @320@%0\32; @320@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @320@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '320'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 320

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (321)

#define @321@%0\32; @321@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @321@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '321'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 321

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (322)

#define @322@%0\32; @322@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @322@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '322'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 322

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (323)

#define @323@%0\32; @323@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @323@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '323'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 323

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (324)

#define @324@%0\32; @324@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @324@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '324'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 324

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (325)

#define @325@%0\32; @325@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @325@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '325'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 325

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (326)

#define @326@%0\32; @326@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @326@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '326'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 326

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (327)

#define @327@%0\32; @327@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @327@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '327'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 327

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (328)

#define @328@%0\32; @328@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @328@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '328'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 328

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (329)

#define @329@%0\32; @329@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @329@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '329'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 329

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (330)

#define @330@%0\32; @330@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @330@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '330'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 330

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (331)

#define @331@%0\32; @331@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @331@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '331'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 331

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (332)

#define @332@%0\32; @332@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @332@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '332'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 332

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (333)

#define @333@%0\32; @333@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @333@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '333'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 333

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (334)

#define @334@%0\32; @334@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @334@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '334'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 334

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (335)

#define @335@%0\32; @335@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @335@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '335'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 335

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (336)

#define @336@%0\32; @336@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @336@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '336'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 336

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (337)

#define @337@%0\32; @337@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @337@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '337'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 337

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (338)

#define @338@%0\32; @338@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @338@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '338'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 338

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (339)

#define @339@%0\32; @339@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @339@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '339'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 339

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (340)

#define @340@%0\32; @340@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @340@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '340'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 340

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (341)

#define @341@%0\32; @341@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @341@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '341'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 341

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (342)

#define @342@%0\32; @342@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @342@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '342'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 342

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (343)

#define @343@%0\32; @343@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @343@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '343'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 343

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (344)

#define @344@%0\32; @344@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @344@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '344'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 344

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (345)

#define @345@%0\32; @345@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @345@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '345'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 345

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (346)

#define @346@%0\32; @346@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @346@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '346'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 346

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (347)

#define @347@%0\32; @347@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @347@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '347'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 347

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (348)

#define @348@%0\32; @348@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @348@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '348'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 348

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (349)

#define @349@%0\32; @349@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @349@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '349'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 349

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (350)

#define @350@%0\32; @350@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @350@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '350'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 350

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (351)

#define @351@%0\32; @351@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @351@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '351'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 351

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (352)

#define @352@%0\32; @352@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @352@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '352'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 352

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (353)

#define @353@%0\32; @353@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @353@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '353'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 353

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (354)

#define @354@%0\32; @354@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @354@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '354'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 354

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (355)

#define @355@%0\32; @355@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @355@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '355'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 355

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (356)

#define @356@%0\32; @356@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @356@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '356'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 356

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (357)

#define @357@%0\32; @357@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @357@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '357'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 357

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (358)

#define @358@%0\32; @358@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @358@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '358'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 358

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (359)

#define @359@%0\32; @359@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @359@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '359'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 359

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (360)

#define @360@%0\32; @360@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @360@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '360'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 360

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (361)

#define @361@%0\32; @361@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @361@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '361'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 361

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (362)

#define @362@%0\32; @362@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @362@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '362'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 362

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (363)

#define @363@%0\32; @363@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @363@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '363'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 363

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (364)

#define @364@%0\32; @364@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @364@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '364'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 364

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (365)

#define @365@%0\32; @365@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @365@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '365'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 365

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (366)

#define @366@%0\32; @366@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @366@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '366'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 366

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (367)

#define @367@%0\32; @367@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @367@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '367'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 367

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (368)

#define @368@%0\32; @368@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @368@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '368'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 368

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (369)

#define @369@%0\32; @369@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @369@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '369'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 369

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (370)

#define @370@%0\32; @370@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @370@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '370'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 370

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (371)

#define @371@%0\32; @371@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @371@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '371'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 371

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (372)

#define @372@%0\32; @372@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @372@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '372'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 372

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (373)

#define @373@%0\32; @373@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @373@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '373'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 373

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (374)

#define @374@%0\32; @374@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @374@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '374'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 374

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (375)

#define @375@%0\32; @375@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @375@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '375'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 375

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (376)

#define @376@%0\32; @376@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @376@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '376'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 376

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (377)

#define @377@%0\32; @377@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @377@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '377'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 377

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (378)

#define @378@%0\32; @378@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @378@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '378'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 378

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (379)

#define @379@%0\32; @379@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @379@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '379'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 379

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (380)

#define @380@%0\32; @380@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @380@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '380'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 380

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (381)

#define @381@%0\32; @381@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @381@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '381'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 381

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (382)

#define @382@%0\32; @382@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @382@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '382'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 382

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (383)

#define @383@%0\32; @383@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @383@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '383'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 383

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (384)

#define @384@%0\32; @384@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @384@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '384'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 384

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (385)

#define @385@%0\32; @385@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @385@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '385'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 385

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (386)

#define @386@%0\32; @386@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @386@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '386'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 386

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (387)

#define @387@%0\32; @387@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @387@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '387'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 387

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (388)

#define @388@%0\32; @388@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @388@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '388'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 388

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (389)

#define @389@%0\32; @389@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @389@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '389'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 389

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (390)

#define @390@%0\32; @390@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @390@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '390'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 390

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (391)

#define @391@%0\32; @391@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @391@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '391'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 391

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (392)

#define @392@%0\32; @392@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @392@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '392'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 392

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (393)

#define @393@%0\32; @393@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @393@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '393'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 393

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (394)

#define @394@%0\32; @394@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @394@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '394'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 394

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (395)

#define @395@%0\32; @395@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @395@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '395'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 395

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (396)

#define @396@%0\32; @396@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @396@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '396'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 396

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (397)

#define @397@%0\32; @397@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @397@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '397'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 397

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (398)

#define @398@%0\32; @398@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @398@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '398'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 398

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (399)

#define @399@%0\32; @399@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @399@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '399'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 399

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (400)

#define @400@%0\32; @400@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @400@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '400'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 400

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (401)

#define @401@%0\32; @401@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @401@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '401'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 401

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (402)

#define @402@%0\32; @402@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @402@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '402'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 402

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (403)

#define @403@%0\32; @403@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @403@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '403'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 403

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (404)

#define @404@%0\32; @404@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @404@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '404'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 404

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (405)

#define @405@%0\32; @405@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @405@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '405'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 405

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (406)

#define @406@%0\32; @406@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @406@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '406'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 406

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (407)

#define @407@%0\32; @407@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @407@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '407'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 407

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (408)

#define @408@%0\32; @408@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @408@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '408'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 408

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (409)

#define @409@%0\32; @409@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @409@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '409'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 409

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (410)

#define @410@%0\32; @410@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @410@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '410'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 410

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (411)

#define @411@%0\32; @411@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @411@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '411'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 411

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (412)

#define @412@%0\32; @412@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @412@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '412'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 412

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (413)

#define @413@%0\32; @413@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @413@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '413'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 413

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (414)

#define @414@%0\32; @414@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @414@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '414'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 414

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (415)

#define @415@%0\32; @415@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @415@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '415'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 415

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (416)

#define @416@%0\32; @416@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @416@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '416'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 416

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (417)

#define @417@%0\32; @417@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @417@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '417'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 417

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (418)

#define @418@%0\32; @418@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @418@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '418'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 418

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (419)

#define @419@%0\32; @419@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @419@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '419'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 419

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (420)

#define @420@%0\32; @420@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @420@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '420'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 420

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (421)

#define @421@%0\32; @421@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @421@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '421'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 421

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (422)

#define @422@%0\32; @422@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @422@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '422'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 422

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (423)

#define @423@%0\32; @423@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @423@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '423'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 423

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (424)

#define @424@%0\32; @424@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @424@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '424'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 424

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (425)

#define @425@%0\32; @425@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @425@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '425'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 425

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (426)

#define @426@%0\32; @426@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @426@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '426'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 426

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (427)

#define @427@%0\32; @427@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @427@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '427'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 427

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (428)

#define @428@%0\32; @428@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @428@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '428'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 428

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (429)

#define @429@%0\32; @429@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @429@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '429'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 429

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (430)

#define @430@%0\32; @430@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @430@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '430'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 430

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (431)

#define @431@%0\32; @431@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @431@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '431'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 431

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (432)

#define @432@%0\32; @432@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @432@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '432'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 432

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (433)

#define @433@%0\32; @433@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @433@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '433'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 433

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (434)

#define @434@%0\32; @434@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @434@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '434'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 434

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (435)

#define @435@%0\32; @435@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @435@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '435'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 435

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (436)

#define @436@%0\32; @436@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @436@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '436'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 436

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (437)

#define @437@%0\32; @437@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @437@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '437'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 437

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (438)

#define @438@%0\32; @438@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @438@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '438'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 438

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (439)

#define @439@%0\32; @439@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @439@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '439'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 439

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (440)

#define @440@%0\32; @440@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @440@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '440'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 440

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (441)

#define @441@%0\32; @441@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @441@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '441'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 441

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (442)

#define @442@%0\32; @442@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @442@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '442'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 442

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (443)

#define @443@%0\32; @443@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @443@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '443'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 443

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (444)

#define @444@%0\32; @444@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @444@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '444'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 444

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (445)

#define @445@%0\32; @445@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @445@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '445'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 445

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (446)

#define @446@%0\32; @446@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @446@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '446'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 446

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (447)

#define @447@%0\32; @447@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @447@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '447'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 447

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (448)

#define @448@%0\32; @448@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @448@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '448'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 448

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (449)

#define @449@%0\32; @449@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @449@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '449'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 449

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (450)

#define @450@%0\32; @450@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @450@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '450'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 450

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (451)

#define @451@%0\32; @451@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @451@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '451'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 451

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (452)

#define @452@%0\32; @452@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @452@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '452'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 452

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (453)

#define @453@%0\32; @453@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @453@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '453'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 453

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (454)

#define @454@%0\32; @454@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @454@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '454'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 454

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (455)

#define @455@%0\32; @455@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @455@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '455'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 455

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (456)

#define @456@%0\32; @456@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @456@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '456'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 456

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (457)

#define @457@%0\32; @457@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @457@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '457'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 457

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (458)

#define @458@%0\32; @458@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @458@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '458'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 458

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (459)

#define @459@%0\32; @459@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @459@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '459'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 459

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (460)

#define @460@%0\32; @460@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @460@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '460'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 460

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (461)

#define @461@%0\32; @461@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @461@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '461'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 461

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (462)

#define @462@%0\32; @462@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @462@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '462'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 462

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (463)

#define @463@%0\32; @463@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @463@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '463'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 463

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (464)

#define @464@%0\32; @464@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @464@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '464'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 464

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (465)

#define @465@%0\32; @465@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @465@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '465'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 465

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (466)

#define @466@%0\32; @466@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @466@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '466'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 466

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (467)

#define @467@%0\32; @467@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @467@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '467'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 467

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (468)

#define @468@%0\32; @468@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @468@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '468'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 468

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (469)

#define @469@%0\32; @469@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @469@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '469'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 469

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (470)

#define @470@%0\32; @470@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @470@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '470'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 470

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (471)

#define @471@%0\32; @471@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @471@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '471'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 471

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (472)

#define @472@%0\32; @472@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @472@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '472'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 472

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (473)

#define @473@%0\32; @473@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @473@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '473'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 473

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (474)

#define @474@%0\32; @474@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @474@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '474'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 474

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (475)

#define @475@%0\32; @475@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @475@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '475'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 475

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (476)

#define @476@%0\32; @476@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @476@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '476'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 476

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (477)

#define @477@%0\32; @477@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @477@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '477'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 477

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (478)

#define @478@%0\32; @478@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @478@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '478'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 478

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (479)

#define @479@%0\32; @479@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @479@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '479'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 479

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (480)

#define @480@%0\32; @480@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @480@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '480'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 480

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (481)

#define @481@%0\32; @481@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @481@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '481'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 481

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (482)

#define @482@%0\32; @482@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @482@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '482'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 482

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (483)

#define @483@%0\32; @483@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @483@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '483'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 483

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (484)

#define @484@%0\32; @484@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @484@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '484'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 484

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (485)

#define @485@%0\32; @485@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @485@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '485'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 485

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (486)

#define @486@%0\32; @486@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @486@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '486'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 486

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (487)

#define @487@%0\32; @487@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @487@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '487'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 487

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (488)

#define @488@%0\32; @488@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @488@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '488'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 488

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (489)

#define @489@%0\32; @489@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @489@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '489'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 489

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (490)

#define @490@%0\32; @490@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @490@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '490'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 490

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (491)

#define @491@%0\32; @491@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @491@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '491'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 491

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (492)

#define @492@%0\32; @492@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @492@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '492'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 492

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (493)

#define @493@%0\32; @493@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @493@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '493'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 493

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (494)

#define @494@%0\32; @494@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @494@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '494'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 494

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (495)

#define @495@%0\32; @495@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @495@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '495'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 495

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (496)

#define @496@%0\32; @496@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @496@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '496'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 496

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (497)

#define @497@%0\32; @497@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @497@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '497'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 497

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (498)

#define @498@%0\32; @498@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @498@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '498'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 498

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (499)

#define @499@%0\32; @499@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @499@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '499'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 499

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (500)

#define @500@%0\32; @500@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @500@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '500'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 500

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (501)

#define @501@%0\32; @501@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @501@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '501'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 501

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (502)

#define @502@%0\32; @502@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @502@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '502'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 502

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (503)

#define @503@%0\32; @503@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @503@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '503'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 503

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (504)

#define @504@%0\32; @504@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @504@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '504'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 504

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (505)

#define @505@%0\32; @505@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @505@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '505'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 505

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (506)

#define @506@%0\32; @506@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @506@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '506'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 506

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (507)

#define @507@%0\32; @507@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @507@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '507'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 507

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (508)

#define @508@%0\32; @508@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @508@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '508'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 508

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (509)

#define @509@%0\32; @509@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @509@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '509'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 509

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (510)

#define @510@%0\32; @510@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @510@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '510'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 510

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (511)

#define @511@%0\32; @511@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @511@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '511'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 511

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (512)

#define @512@%0\32; @512@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @512@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '512'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 512

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (513)

#define @513@%0\32; @513@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @513@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '513'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 513

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (514)

#define @514@%0\32; @514@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @514@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '514'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 514

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (515)

#define @515@%0\32; @515@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @515@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '515'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 515

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (516)

#define @516@%0\32; @516@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @516@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '516'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 516

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (517)

#define @517@%0\32; @517@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @517@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '517'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 517

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (518)

#define @518@%0\32; @518@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @518@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '518'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 518

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (519)

#define @519@%0\32; @519@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @519@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '519'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 519

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (520)

#define @520@%0\32; @520@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @520@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '520'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 520

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (521)

#define @521@%0\32; @521@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @521@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '521'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 521

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (522)

#define @522@%0\32; @522@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @522@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '522'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 522

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (523)

#define @523@%0\32; @523@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @523@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '523'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 523

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (524)

#define @524@%0\32; @524@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @524@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '524'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 524

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (525)

#define @525@%0\32; @525@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @525@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '525'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 525

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (526)

#define @526@%0\32; @526@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @526@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '526'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 526

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (527)

#define @527@%0\32; @527@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @527@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '527'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 527

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (528)

#define @528@%0\32; @528@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @528@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '528'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 528

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (529)

#define @529@%0\32; @529@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @529@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '529'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 529

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (530)

#define @530@%0\32; @530@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @530@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '530'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 530

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (531)

#define @531@%0\32; @531@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @531@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '531'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 531

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (532)

#define @532@%0\32; @532@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @532@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '532'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 532

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (533)

#define @533@%0\32; @533@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @533@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '533'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 533

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (534)

#define @534@%0\32; @534@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @534@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '534'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 534

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (535)

#define @535@%0\32; @535@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @535@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '535'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 535

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (536)

#define @536@%0\32; @536@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @536@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '536'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 536

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (537)

#define @537@%0\32; @537@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @537@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '537'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 537

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (538)

#define @538@%0\32; @538@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @538@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '538'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 538

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (539)

#define @539@%0\32; @539@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @539@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '539'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 539

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (540)

#define @540@%0\32; @540@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @540@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '540'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 540

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (541)

#define @541@%0\32; @541@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @541@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '541'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 541

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (542)

#define @542@%0\32; @542@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @542@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '542'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 542

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (543)

#define @543@%0\32; @543@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @543@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '543'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 543

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (544)

#define @544@%0\32; @544@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @544@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '544'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 544

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (545)

#define @545@%0\32; @545@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @545@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '545'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 545

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (546)

#define @546@%0\32; @546@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @546@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '546'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 546

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (547)

#define @547@%0\32; @547@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @547@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '547'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 547

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (548)

#define @548@%0\32; @548@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @548@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '548'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 548

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (549)

#define @549@%0\32; @549@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @549@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '549'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 549

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (550)

#define @550@%0\32; @550@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @550@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '550'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 550

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (551)

#define @551@%0\32; @551@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @551@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '551'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 551

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (552)

#define @552@%0\32; @552@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @552@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '552'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 552

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (553)

#define @553@%0\32; @553@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @553@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '553'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 553

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (554)

#define @554@%0\32; @554@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @554@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '554'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 554

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (555)

#define @555@%0\32; @555@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @555@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '555'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 555

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (556)

#define @556@%0\32; @556@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @556@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '556'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 556

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (557)

#define @557@%0\32; @557@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @557@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '557'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 557

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (558)

#define @558@%0\32; @558@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @558@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '558'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 558

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (559)

#define @559@%0\32; @559@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @559@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '559'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 559

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (560)

#define @560@%0\32; @560@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @560@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '560'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 560

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (561)

#define @561@%0\32; @561@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @561@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '561'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 561

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (562)

#define @562@%0\32; @562@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @562@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '562'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 562

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (563)

#define @563@%0\32; @563@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @563@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '563'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 563

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (564)

#define @564@%0\32; @564@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @564@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '564'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 564

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (565)

#define @565@%0\32; @565@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @565@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '565'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 565

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (566)

#define @566@%0\32; @566@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @566@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '566'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 566

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (567)

#define @567@%0\32; @567@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @567@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '567'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 567

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (568)

#define @568@%0\32; @568@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @568@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '568'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 568

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (569)

#define @569@%0\32; @569@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @569@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '569'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 569

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (570)

#define @570@%0\32; @570@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @570@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '570'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 570

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (571)

#define @571@%0\32; @571@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @571@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '571'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 571

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (572)

#define @572@%0\32; @572@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @572@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '572'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 572

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (573)

#define @573@%0\32; @573@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @573@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '573'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 573

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (574)

#define @574@%0\32; @574@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @574@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '574'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 574

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (575)

#define @575@%0\32; @575@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @575@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '575'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 575

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (576)

#define @576@%0\32; @576@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @576@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '576'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 576

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (577)

#define @577@%0\32; @577@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @577@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '577'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 577

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (578)

#define @578@%0\32; @578@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @578@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '578'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 578

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (579)

#define @579@%0\32; @579@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @579@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '579'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 579

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (580)

#define @580@%0\32; @580@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @580@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '580'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 580

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (581)

#define @581@%0\32; @581@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @581@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '581'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 581

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (582)

#define @582@%0\32; @582@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @582@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '582'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 582

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (583)

#define @583@%0\32; @583@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @583@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '583'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 583

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (584)

#define @584@%0\32; @584@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @584@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '584'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 584

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (585)

#define @585@%0\32; @585@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @585@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '585'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 585

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (586)

#define @586@%0\32; @586@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @586@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '586'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 586

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (587)

#define @587@%0\32; @587@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @587@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '587'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 587

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (588)

#define @588@%0\32; @588@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @588@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '588'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 588

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (589)

#define @589@%0\32; @589@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @589@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '589'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 589

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (590)

#define @590@%0\32; @590@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @590@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '590'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 590

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (591)

#define @591@%0\32; @591@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @591@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '591'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 591

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (592)

#define @592@%0\32; @592@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @592@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '592'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 592

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (593)

#define @593@%0\32; @593@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @593@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '593'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 593

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (594)

#define @594@%0\32; @594@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @594@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '594'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 594

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (595)

#define @595@%0\32; @595@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @595@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '595'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 595

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (596)

#define @596@%0\32; @596@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @596@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '596'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 596

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (597)

#define @597@%0\32; @597@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @597@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '597'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 597

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (598)

#define @598@%0\32; @598@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @598@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '598'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 598

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (599)

#define @599@%0\32; @599@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @599@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '599'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 599

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (600)

#define @600@%0\32; @600@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @600@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '600'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 600

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (601)

#define @601@%0\32; @601@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @601@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '601'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 601

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (602)

#define @602@%0\32; @602@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @602@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '602'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 602

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (603)

#define @603@%0\32; @603@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @603@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '603'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 603

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (604)

#define @604@%0\32; @604@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @604@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '604'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 604

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (605)

#define @605@%0\32; @605@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @605@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '605'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 605

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (606)

#define @606@%0\32; @606@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @606@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '606'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 606

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (607)

#define @607@%0\32; @607@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @607@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '607'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 607

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (608)

#define @608@%0\32; @608@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @608@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '608'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 608

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (609)

#define @609@%0\32; @609@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @609@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '609'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 609

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (610)

#define @610@%0\32; @610@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @610@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '610'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 610

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (611)

#define @611@%0\32; @611@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @611@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '611'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 611

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (612)

#define @612@%0\32; @612@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @612@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '612'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 612

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (613)

#define @613@%0\32; @613@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @613@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '613'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 613

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (614)

#define @614@%0\32; @614@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @614@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '614'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 614

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (615)

#define @615@%0\32; @615@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @615@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '615'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 615

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (616)

#define @616@%0\32; @616@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @616@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '616'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 616

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (617)

#define @617@%0\32; @617@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @617@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '617'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 617

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (618)

#define @618@%0\32; @618@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @618@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '618'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 618

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (619)

#define @619@%0\32; @619@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @619@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '619'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 619

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (620)

#define @620@%0\32; @620@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @620@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '620'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 620

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (621)

#define @621@%0\32; @621@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @621@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '621'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 621

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (622)

#define @622@%0\32; @622@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @622@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '622'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 622

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (623)

#define @623@%0\32; @623@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @623@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '623'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 623

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (624)

#define @624@%0\32; @624@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @624@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '624'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 624

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (625)

#define @625@%0\32; @625@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @625@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '625'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 625

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (626)

#define @626@%0\32; @626@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @626@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '626'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 626

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (627)

#define @627@%0\32; @627@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @627@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '627'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 627

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (628)

#define @628@%0\32; @628@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @628@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '628'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 628

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (629)

#define @629@%0\32; @629@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @629@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '629'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 629

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (630)

#define @630@%0\32; @630@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @630@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '630'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 630

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (631)

#define @631@%0\32; @631@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @631@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '631'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 631

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (632)

#define @632@%0\32; @632@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @632@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '632'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 632

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (633)

#define @633@%0\32; @633@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @633@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '633'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 633

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (634)

#define @634@%0\32; @634@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @634@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '634'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 634

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (635)

#define @635@%0\32; @635@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @635@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '635'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 635

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (636)

#define @636@%0\32; @636@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @636@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '636'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 636

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (637)

#define @637@%0\32; @637@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @637@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '637'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 637

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (638)

#define @638@%0\32; @638@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @638@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '638'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 638

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (639)

#define @639@%0\32; @639@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @639@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '639'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 639

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (640)

#define @640@%0\32; @640@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @640@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '640'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 640

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (641)

#define @641@%0\32; @641@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @641@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '641'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 641

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (642)

#define @642@%0\32; @642@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @642@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '642'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 642

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (643)

#define @643@%0\32; @643@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @643@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '643'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 643

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (644)

#define @644@%0\32; @644@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @644@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '644'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 644

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (645)

#define @645@%0\32; @645@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @645@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '645'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 645

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (646)

#define @646@%0\32; @646@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @646@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '646'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 646

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (647)

#define @647@%0\32; @647@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @647@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '647'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 647

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (648)

#define @648@%0\32; @648@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @648@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '648'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 648

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (649)

#define @649@%0\32; @649@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @649@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '649'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 649

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (650)

#define @650@%0\32; @650@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @650@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '650'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 650

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (651)

#define @651@%0\32; @651@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @651@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '651'.
#endif

#endinput

#elseif DETUTILSGLOBAL_IDX == 651

#undef DETUTILSGLOBAL_IDX
#define DETUTILSGLOBAL_IDX (652)

#define @652@%0\32; @652@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @652@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '652'.
#endif

#endinput

#endif

#else

//#define d_als_included
#define DETUTILSGLOBAL_IDX (0)

#define @0@%0\32; @0@
#define @DETUTILSGLOBAL_FUNC__$%1..%2$ @0@%1(%2)

#if defined DETUTILS_DEBUG_MODE
#warning [DETUtils]: (debug) - DETUTILSGLOBAL_IDX is '0'.
#endif

#endif