/*
 * 
 * SA:MP DEntisT's Utilities
 *
 * Since 2019., DEntisT
 *
 *
 *
 * - Library core file.
 *
 *
 */

// d_properties

#define DETUTILS_TEXT_MAX_PROPS_REACH "Maximum number of created properties reached."
#define DETUTILS_TEXT_PROPERTY_NAME "Property: %s"

// d_commands

#define DETUTILS_TEXT_UNK_PRX_FUNC "Prefix function name for command %s doesn't exist."

#define DETUTILS_TEXT_CHATMODE_PRX "SERVER: Chat mode switched to custom-prefixed commands mode."
#define DETUTILS_TEXT_CHATMODE_MSG "SERVER: Chat mode switched to plain-text messages mode."

// d_fmargs

// d_visual

#define DETUTILS_TEXT_MAX_GUN_REACH "Maximum number of dropped gun objects reached."
#define DETUTILS_TEXT_CMD_TIMER "The player tried to use the command but the timer was not over yet."
#define DETUTILS_TEXT_CANNOT_OPERATE ""COLOUR_GREY"Operation can't be completed at the moment."
#define DETUTILS_TEXT_THROW_GUN ""COLOUR_GREY"You threw away {ffffff}%s"COLOUR_GREY"."
#define DETUTILS_TEXT_NOGUN_NEARBY ""COLOUR_GREY"No guns nearby."
#define DETUTILS_TEXT_GUN_DESTROY ""COLOUR_GREY"You destroyed {ffffff}%s"COLOUR_GREY"."
#define DETUTILS_TEXT_GUN_PICK ""COLOUR_GREY"You picked up {ffffff}%s"COLOUR_GREY"."

// d_anticheat

// d_colours