/*
 * 
 * SA:MP DEntisT's Utilities
 *
 * Since 2019., DEntisT
 *
 *
 *
 * - Library which provides 
 *   Pawn implementation
 *   of 'sscanf'.
 *
 */

#if defined DETUTIS_NO_SSCANF

	#endinput

#endif

/*
										 
88                                   88  
88                                   88  
88                                   88  
88  88,dPYba,,adPYba,   8b,dPPYba,   88  
88  88P'   "88"    "8a  88P'    "8a  88  
88  88      88      88  88       d8  88  
88  88      88      88  88b,   ,a8"  88  
88  88      88      88  88`YbbdP"'   88  
------------------------88-------------  
------------------------88-------------

*/

#define @DETUTILSSSCANF_KEYWORD__@%0\32; @DETUTILSSSCANF_KEYWORD__@
#define sscanf @DETUTILSSSCANF_KEYWORD__@

#define @DETUTILSSSCANF_KEYWORD__@