/*
 * 
 * DETUtils
 *
 * Since 2019., DEntisT
 *
 *
 *
 * - Macros for d_discordutils.inc
 *
 *
 */

#define @DETUTILSDCDATA_DEC__@%0\32; @DETUTILSDCDATA_DEC__@
#define @discord%0(%1.entity%2= @DETUTILSDCDATA_DEC__@

/*
                                                                                      
88b           d88              88                         db         88888888ba   88  
888b         d888              ""                        d88b        88      "8b  88  
88`8b       d8'88                                       d8'`8b       88      ,8P  88  
88 `8b     d8' 88  ,adPPYYba,  88  8b,dPPYba,          d8'  `8b      88aaaaaa8P'  88  
88  `8b   d8'  88  ""     `Y8  88  88P'   `"8a        d8YaaaaY8b     88""""""'    88  
88   `8b d8'   88  ,adPPPPP88  88  88       88       d8""""""""8b    88           88  
88    `888'    88  88,    ,88  88  88       88      d8'        `8b   88           88  
88     `8'     88  `"8bbdP"Y8  88  88       88     d8'          `8b  88           88  
                                                                                      
                                                                                      
*/

#define @DETUTILSDCDATA_DEC__@GUILD%0)%1SetIntegerData(%2) __SetGuildData_Integer(%2)
#define @DETUTILSDCDATA_DEC__@GUILD%0)%1GetIntegerData(%2) __GetGuildData_Integer(%2)
#define @DETUTILSDCDATA_DEC__@GUILD%0)%1SetBooleanData(%2) __SetGuildData_Boolean(%2)
#define @DETUTILSDCDATA_DEC__@GUILD%0)%1GetBooleanData(%2) __GetGuildData_Boolean(%2)
#define @DETUTILSDCDATA_DEC__@GUILD%0)%1SetFloatData(%2) __SetGuildData_Float(%2)
#define @DETUTILSDCDATA_DEC__@GUILD%0)%1GetFloatData(%2) __GetGuildData_Float(%2)
#define @DETUTILSDCDATA_DEC__@GUILD%0)%1SetStringData(%2) __SetGuildData_String(%2)
#define @DETUTILSDCDATA_DEC__@GUILD%0)%1GetStringData(%2) __GetGuildData_String(%2)
#define @DETUTILSDCDATA_DEC__@CHANNEL%0)%1SetIntegerData(%2) __SetChannelData_Integer(%2)
#define @DETUTILSDCDATA_DEC__@CHANNEL%0)%1GetIntegerData(%2) __GetChannelData_Integer(%2)
#define @DETUTILSDCDATA_DEC__@CHANNEL%0)%1SetBooleanData(%2) __SetChannelData_Boolean(%2)
#define @DETUTILSDCDATA_DEC__@CHANNEL%0)%1GetBooleanData(%2) __GetChannelData_Boolean(%2)
#define @DETUTILSDCDATA_DEC__@CHANNEL%0)%1SetFloatData(%2) __SetChannelData_Float(%2)
#define @DETUTILSDCDATA_DEC__@CHANNEL%0)%1GetFloatData(%2) __GetChannelData_Float(%2)
#define @DETUTILSDCDATA_DEC__@CHANNEL%0)%1SetStringData(%2) __SetChannelData_String(%2)
#define @DETUTILSDCDATA_DEC__@CHANNEL%0)%1GetStringData(%2) __GetChannelData_String(%2)
#define @DETUTILSDCDATA_DEC__@USER%0)%1SetIntegerData(%2) __SetUserData_Integer(%2)
#define @DETUTILSDCDATA_DEC__@USER%0)%1GetIntegerData(%2) __GetUserData_Integer(%2)
#define @DETUTILSDCDATA_DEC__@USER%0)%1SetBooleanData(%2) __SetUserData_Boolean(%2)
#define @DETUTILSDCDATA_DEC__@USER%0)%1GetBooleanData(%2) __GetUserData_Boolean(%2)
#define @DETUTILSDCDATA_DEC__@USER%0)%1SetFloatData(%2) __SetUserData_Float(%2)
#define @DETUTILSDCDATA_DEC__@USER%0)%1GetFloatData(%2) __GetUserData_Float(%2)
#define @DETUTILSDCDATA_DEC__@USER%0)%1SetStringData(%2) __SetUserData_String(%2)
#define @DETUTILSDCDATA_DEC__@USER%0)%1GetStringData(%2) __GetUserData_String(%2)